# Generated by Django 4.2.1 on 2023-06-30 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pfam_id", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("start", models.IntegerField()),
                ("stop", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Organism",
            fields=[
                ("taxa_id", models.IntegerField(primary_key=True, serialize=False)),
                ("genus", models.CharField(max_length=100)),
                ("species", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Protein",
            fields=[
                ("custom_pk", models.AutoField(primary_key=True, serialize=False)),
                ("protein_id", models.CharField(max_length=100)),
                ("clade", models.CharField(max_length=100)),
                ("length", models.IntegerField()),
                ("pfam_id", models.CharField(max_length=100)),
                (
                    "taxa_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="midtermBioData.organism",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PfamID",
            fields=[
                (
                    "domain_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="midtermBioData.domain",
                    ),
                ),
                ("domain_description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "protein_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="midtermBioData.protein",
                    ),
                ),
                ("sequence", models.CharField(max_length=600)),
            ],
        ),
        migrations.AddField(
            model_name="domain",
            name="protein_id",
            field=models.ManyToManyField(to="midtermBioData.protein"),
        ),
    ]
