# Generated by Django 4.2.1 on 2023-07-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("midtermBioData", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protein",
            name="custom_pk",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
