# Generated by Django 4.2.2 on 2023-07-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("midtermBioData", "0005_sequence_id_alter_sequence_protein_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="protein_id",
            field=models.ManyToManyField(
                related_name="domains", to="midtermBioData.protein"
            ),
        ),
    ]
